---
strictness: high

doc-warnings: true

mccabe:
  options:
    max-complexity: 16

pycodestyle:
  disable:
    - E203 # Whitespace before ':', duplicated with black, with error in array
    - E722 # do not use bare 'except', duplicated with pylint
    - E261 # at least two spaces before inline comment, duplicated with black

pydocstyle:
  disable:
    - D105 # Missing docstring in magic method
    - D203 # 1 blank line required before class docstring (found 0)
    - D213 # Multi-line docstring summary should start at the second line

pylint:
  options:
    extension-pkg-allow-list: re2
